### ISSUE TITLE
HW05: SegFault на некорректной программе

### ISSUE THREAD

**Issue by kajigor** [Glebanister/prolog#1]
[e08.txt](https://github.com/Glebanister/prolog/files/5364719/e08.txt)

```
 15791 Segmentation fault      (core dumped)
```

**Comment by kajigor** [comment]
Также на этой
[e17.txt](https://github.com/Glebanister/prolog/files/5364730/e17.txt)

**Comment by Glebanister** [comment]
Исправлено
